### ISSUE TITLE
where is the linux version? 

### ISSUE THREAD

**Issue by MonoMit** [huantianad/LevelSync#7]
hi, im the person who reported the memory usage thingy, but may i ask how to use the linux version, im on the linux system and are wondering how to use it.

i assume its the levelsync file in the release page, running it gave me 
```
emily@emily ~> /home/emily/Downloads/levelsync
No stack traceback available
Error: unhandled exception: lexbase.nim(138, 9) `input != nil`  [AssertionDefect]
```
i have no idea how to run it properly :sweat:

**Comment by MonoMit** [comment]
okay nevermind, found out how, needed to install nim, then it runs perfectly

**Comment by huantianad** [comment]
I know your issue is solved, but could you help me do some testing? Ideally the program wouldn’t need Nim installed to work.

**Comment by MonoMit** [comment]
sure, what do i have to do

**Comment by huantianad** [comment]
Ah nevermind, I see the problem now. The error is due to the config file not being present next to the executable. Can you uninstall Nim and run the program again (with a config file next to it) and see if it works still?

**Comment by MonoMit** [comment]
oh hey, yes it works now, i didnt need to install nim, just needed the config file like you said. :derp:

**Comment by MonoMit** [comment]
maybe you should update the readme to include that for linux users

**Comment by huantianad** [comment]
I've made a new release which should mark the linux version as linux in the file name, and also come with the config file as well.
Edit: also yeah I think I'll update the readme too, thanks for the heads up!

**Comment by MonoMit** [comment]
thanks for the help :pray: 
and good to hear
